### ISSUE TITLE
Brak dokumentacji projektu

### ISSUE THREAD

**Issue by mmiklas** [wer-bena/health-assisstant-app#1]
Ponieważ projekt nie jest hostowany na Heroku i aby zobaczyć go w działaniu muszę ponieść wysiłek i uruchomić go samodzielnie to krótka instrukcja nie tylko opisu samego projektu ale też sposobu uruchomienia była by bardzo pomocna i jest zapisana jako jeden z wymogów.

**Comment by wer-bena** [comment]
Dodana dokumentacja odnośnie sposobu uruchamiania i konfiguracji projektu.
